const ENCOURAGEMENTS = [
  "Drop in and dominate.",
  "Stick the landing.",
  "Shred it.",
  "No bails today.",
  "Grind it out.",
  "Roll with it.",
  "Land every trick.",
  "Skaters don't quit.",
  "Ollie over it.",
  "Full send.",
  "Sessions don't stop.",
  "Keep rolling.",
  "Hit the ramp.",
  "Skate or ace it.",
  "On board and ready.",
  "You got this.",
  "Let's go!",
  "Game time.",
  "All day.",
  "Easy work.",
  "Built for this.",
  "Lock in.",
  "Let's run it.",
  "Time to shine.",
  "Show up.",
  "Go get it.",
  "This is your moment.",
  "Send it.",
  "Go off.",
  "You know this.",
  "Trust your brain.",
  "You've done harder things.",
  "Smarter every day.",
  "This is nothing for you.",
  "You've got the skills.",
  "Already in your head.",
  "Piece of cake.",
  "You were made for this.",
  "Your brain is a weapon.",
  "Nothing can stop you.",
  "The answers are in there.",
  "You belong here.",
  "Confidence is the move.",
  "Believe it.",
  "Bring the heat.",
  "Hard? Good.",
  "Challenges make you stronger.",
  "Earn it.",
  "The harder the better.",
  "Level up time.",
  "Push through it.",
  "Rise to it.",
  "Big moves only.",
  "Don't flinch.",
  "Take it on.",
  "Make it look easy.",
  "Prove it.",
  "Own it.",
  "Do the work.",
  "Breathe and think.",
  "Slow down, speed up.",
  "Take your time.",
  "One at a time.",
  "Stay in it.",
  "Focus in.",
  "Quiet the noise.",
  "Sharp mind, sharp answers.",
  "Zero distractions.",
  "Just you and the math.",
  "Calm is a superpower.",
  "Think first.",
  "Settle in.",
  "Numbers fear you.",
  "Math has met its match.",
  "Calculate greatness.",
  "The answer is waiting on you.",
  "Crush the numbers.",
  "You speak math fluently.",
  "Equations can't hide from you.",
  "Math is your playground.",
  "The digits are on your side.",
  "Run the numbers.",
  "Every rep makes you sharper.",
  "Practice builds champions.",
  "Better every single time.",
  "Progress over perfect.",
  "Reps don't lie.",
  "Show up and level up.",
  "Yesterday's practice pays off today.",
  "Keep stacking wins.",
  "Hard work hits different.",
  "The grind is worth it.",
  "Champions keep going.",
  "One more than yesterday.",
  "Earn your stripes.",
  "The work shows.",
  "Legacy is built in moments like this.",
  "Math? No problem.",
  "This is where it gets fun.",
  "Let the brainwork begin.",
  "Ready to wreck it.",
  "Fast brain, faster answers.",
  "You're on fire.",
  "They can't stop you.",
  "Big brain energy.",
  "No cap, you're ready.",
  "Warming up already.",
]

export function randomEncouragement() {
  return ENCOURAGEMENTS[Math.floor(Math.random() * ENCOURAGEMENTS.length)]
}
